package com.c0x12c.featureflag.models

enum class FeatureFlagType {
  A_B_TESTING_CONFIG,
  CUSTOM_RULES,
  DEVICE_TARGETING,
  GEOGRAPHIC_TARGETING,
  GRADUAL_ROLLOUT,
  GROUP_TARGETING,
  TIME_BASED_ACTIVATION,
  TOGGLE,
  USER_TARGETING,
  VERSION_TARGETING
}
