version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5432:5432"

  redis-cluster:
    image: channguyen/redis-cluster:latest
    restart: always
    ports:
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"
      - "30005:30005"
      - "30006:30006"
