name: Analyze Pull Request

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'manifest.json'
      - '.github/**/*'
      - 'Dockerfile'
      - 'Dockerfile.migration'
      - 'docker-compose.ci.yml'
      - 'tools/**'
      - 'screenshots/**'
      - '.gitignore'
      - '.editorconfig'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:14-3.3
        env:
          POSTGRES_USER: local
          POSTGRES_PASSWORD: local
          POSTGRES_DB: local
        ports:
          - 5432:5432

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Run Redis cluster
        uses: vishnudxb/redis-cluster@1.0.9
        with:
          master1-port: 30001
          master2-port: 30002
          master3-port: 30003
          slave1-port: 30004
          slave2-port: 30005
          slave3-port: 30006

      - name: Run Gradle test
        run: ./gradlew test --no-daemon

      - name: Cache Gradle test results
        uses: actions/cache@v4
        with:
          path: ~/.gradle/test-results
          key: gradle-test-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-test-${{ runner.os }}
