name: Analyze Pull Request

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'manifest.json'
      - '.github/**/*'
      - 'Dockerfile'
      - 'Dockerfile.migration'
      - 'docker-compose.ci.yml'
      - 'tools/**'
      - 'screenshots/**'
      - '.gitignore'
      - '.editorconfig'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:14-3.3
        env:
          POSTGRES_USER: local
          POSTGRES_PASSWORD: local
          POSTGRES_DB: local
        ports:
          - 5432:5432

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Redis cluster
        uses: vishnudxb/redis-cluster@1.0.5
        with:
          master1-port: 30001
          master2-port: 30002
          master3-port: 30003
          slave1-port: 30004
          slave2-port: 30005
          slave3-port: 30006

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build test jacocoTestReport --info

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ steps.github-app-token.outputs.token }}
          file: build/reports/jacoco/test/jacocoTestReport.xml
          format: jacoco